### ISSUE TITLE
Log file being used in other process (by webserver it self)

### ISSUE THREAD

**Issue by Belekz** [Kabindas/IISLogParser#1]
I was wondering how do you handle the fact that your IIS log file is used by the IIS at the same time that you want to read from it, using IISLogParser. 
I receive following error:

`System.IO.IOException: The process cannot access the file because it is being used by another process. `

**Comment by Kabindas** [comment]
Yes, that's true. I believe that with the last changes will fix that problem.
I've just rewrite the ReadAllLines, on the new Utils.cs as well on the ParserEngine.cs when reading lines from the StreamReader, to avoid files locked

**Comment by szyb** [comment]
This solution is not published in nuget, even in pre-release channel. Am I right?
BTW: please add project URL in nuget, it would be easier to find ;) Also license is missing.

**Comment by Kabindas** [comment]
Yes, you're absolute right, I guess the nuget really needs an update, Tnkx m8
